### ISSUE TITLE
自动重启相关问题

### ISSUE THREAD

**Issue by Sakura2466** [Hoshinonyaruko/palworld-go#102]
![QQ图片20240219152105](https://github.com/Hoshinonyaruko/palworld-go/assets/69309140/f7e10eb9-bd75-4930-ba38-dc20ba92f149)
在面板点击重启服务端后，服务端运行正常，但是开服器控制台出现“检测到服务器已手动关闭，不执行重启操作”的字样，有可能会影响服务器内存超过阙值自动重启功能。

**Comment by Hoshinonyaruko** [comment]
已修复。
