### ISSUE TITLE
请问能备份Saved下的所有文件夹吗?或者能自定义备份那些文件夹也可以的.

### ISSUE THREAD

**Issue by SingGor** [Hoshinonyaruko/palworld-go#14]
如题,建议能备份Saved文件夹下的所有文件夹,如包括Config,Crashes,ImGui,Logs,SaveGames;或者自定义只备份哪些文件也可以.因为上次服务更新掉档了,我怀疑是备份不完整导致的,谢谢

**Comment by Hoshinonyaruko** [comment]
已经完善，目前可以了
