### ISSUE TITLE
webui的端口修改没有效果

### ISSUE THREAD

**Issue by VlwsMIR** [Hoshinonyaruko/palworld-go#25]
![{1608DBC0-B470-43e6-B8C2-419B8683C604}](https://github.com/Hoshinonyaruko/palworld-go/assets/123264703/06e8c654-f132-4074-a64a-dfe9b849a42b)
![image](https://github.com/Hoshinonyaruko/palworld-go/assets/123264703/4bf6ca55-c73d-4a52-b1e0-200708e26764)

**Comment by Tardis07** [comment]
#26 这个版本修复了
