### ISSUE TITLE
在linux版本下，默认的账号密码是错误的

### ISSUE THREAD

**Issue by xll98** [Hoshinonyaruko/palworld-go#31]
错误码 401

**Comment by xll98** [comment]
[GIN] 2024/01/28 - 13:16:11 | 401 |     128.745µs |  112.10.224.142 | POST     "/api/login"
2024/01/28 13:16:26 Error fetching players: 未设置密码，检查config.yaml中的password配置

**Comment by Minidoracat** [comment]
沒錯，即使會產生 config.json 也不會讀取，也不會產生 config.yaml

**Comment by Alan315123** [comment]
可以直接尝试用服务器名和管理员密码登录

**Comment by jadezi** [comment]
确实是用PalWorldSettings.ini 里的服务器名和管理员密码登录的

**Comment by Hoshinonyaruko** [comment]
修复了，会有日志提示
