### ISSUE TITLE
RCON中文广播

### ISSUE THREAD

**Issue by ayakasuki** [Hoshinonyaruko/palworld-go#40]
已知游戏里是正常发送中文广播，但是palgo里不行，是不是编码问题呢

**Comment by ayakasuki** [comment]
最新的6.0 dll对linux不起用

**Comment by Minidoracat** [comment]
windows 的測試也是沒有中文
[](https://cdn.discordapp.com/attachments/1199047967739482153/1201850333626900570/image.png)

**Comment by ontisme** [comment]
> windows 的測試也是沒有中文 https://cdn.discordapp.com/attachments/1199047967739482153/1201850333626900570/image.png

+1

**Comment by ontisme** [comment]
替換作者最新的dll即正常

**Comment by ayakasuki** [comment]
> 替換作者最新的dll即正常

win可以啦？希望linux早点也出方案 linux没办法替换dll

**Comment by Minidoracat** [comment]
> > 替換作者最新的dll即正常
> 
> win可以啦？希望linux早点也出方案 linux没办法替换dll

windows 還是要從另外的小視窗才可以發中文
網頁內的不行

**Comment by ayakasuki** [comment]
> 网页内在最新版本得到了支持，需要打开rcon自动注入

linux也可以了嘛
