### ISSUE TITLE
自动重启失效

### ISSUE THREAD

**Issue by Stars-OC** [Hoshinonyaruko/palworld-go#58]
![L9{I)WR9V@B}8I 9 YRG`07](https://github.com/Hoshinonyaruko/palworld-go/assets/41844884/8201bcbd-2a98-45bf-95db-a3e1eaa54ac4)

![TDI5VYUH6X%E0%GQ0O~(LW2](https://github.com/Hoshinonyaruko/palworld-go/assets/41844884/bc079f1d-0fa1-4328-87c2-8eb853484d3d)

如图所示，都正确配置(一般来说用该面板的都是默认开启，按道理没问题。)
然后不能进行自动重启(第一次存档坏了好像也是因为不能自动重启)

**Comment by Hoshinonyaruko** [comment]
rcon的配置，你设置的57495，面板设置的是25575
