### ISSUE TITLE
https证书不识别

### ISSUE THREAD

**Issue by lovepush** [Hoshinonyaruko/palworld-go#61]
我打开了自带的强制https功能，并且将cert.pem和key.pem文件放到了程序exe目录下，但是打开webui提示没有证书。
![微信截图_20240201092028](https://github.com/Hoshinonyaruko/palworld-go/assets/4489128/382ba49e-1360-4926-bb43-d53f34b0b015)
![微信截图_20240201092019](https://github.com/Hoshinonyaruko/palworld-go/assets/4489128/2c6fd12c-3e7d-489f-9a7d-01421ae5cb2d)

**Comment by hwqiangx** [comment]
不会自动识别,放在相同目录后你要填证书和key的文件名

**Comment by Hoshinonyaruko** [comment]
是的
