### ISSUE TITLE
web面板漏洞

### ISSUE THREAD

**Issue by mazafakaer** [Hoshinonyaruko/palworld-go#63]
非常感谢作者提供的非常棒的项目
不过在开启公网访问时，访问此接口能在非登录情况下读取到面版账户密码：
http://xxxxxx/api/getjson
![图片](https://github.com/Hoshinonyaruko/palworld-go/assets/85944863/c5763404-2825-4d09-82c4-651fb5dc9c34)

**Comment by 2022717137** [comment]
感谢，已经在最新版本修复
https://github.com/Hoshinonyaruko/palworld-go/releases/tag/78%2Fmerge

**Comment by AxelPanda** [comment]
似乎在最新版本中仍然存在这个问题，使用隐身模式打开http://xxxxxx/api/getjson仍然能看到管理密码等信息。
