### ISSUE TITLE
[功能建议]服务器自动重启相关功能完善

### ISSUE THREAD

**Issue by eosrce** [Hoshinonyaruko/palworld-go#69]
目前的自动重启完全靠restart.sh实现，但面板中没有关于是否需要开启自动重启的选项。

以及在未运行服务端前先运行面板也会默认自动拉起服务端，但我想要两者独立控制，方便调试。

例如我手动关闭了服务器，但面板又自动开启了服务器，并且我想终止只能用pkill将面板终止（由面板启动的服务端也会被一起终止）。

此外，面板中关于服务端启停控制的相关操作也无法正常实现，也许自动重启策略有关？

所有个人希望可以加上以下功能：

1.是否开启服务端自动重启功能；

2.开启面板时是否启动服务端；

**Comment by Tardis07** [comment]
把守护时间设置为0，面板就不会自动开启服务端

**Comment by eosrce** [comment]
是守护配置修改->定时重启服务端（秒）这个选项吗？

'''
    "gamePath": "/Path",
    "gameSavePath": "/Path",
    "backupPath": "/Path",
    "steamPath": "/Path",
    "communityServer": false,
    "useDll": false,
    "cert": "",
    "key": "",
    "address": "127.0.0.1",
    "usehttps": false,
    "webuiPort": "52000",
    "autoLaunchWebui": true,
    "processName": "PalServer",
    "onebotV11HttpApiPath": "",
    "serverOptions": [
        "-useperfthreads",
        "-NoAsyncLoadingThread",
        "-UseMultithreadForDS"
    ],
    "checkInterval": 300,
    "backupInterval": 600,
    "RestartInterval": 0,
    "memoryCheckInterval": 300,
    "memoryUsageThreshold": 80,
    "totalMemoryGB": 24,
    "memoryCleanupInterval": 1800,
    "regularMessages": [
        "",
        ""
    ],
'''
