### ISSUE TITLE
Problems with server not shutting down

### ISSUE THREAD

**Issue by xczsonn** [Hoshinonyaruko/palworld-go#81]
If i press the Restart Server button on front, run one more palserver program without closing the server, and if i press the Shutdown Server button on front, it will see STOP in the Palworld GO console, but the server will not actually shut down.

**Comment by xczsonn** [comment]
The problem has been fixed, but when booted to a community server, the problem remains the same. Even the console keeps trying to boot Steam. Did I set the wrong Steam path?

Game world settings saved successfully.
Engine settings saved successfully.
[GIN] 2024/02/09 - 07:00:41 | 200 |    1.0104327s |       127.0.0.1 | GET      "/api/status"
[GIN] 2024/02/09 - 07:00:44 | 200 |    1.0076295s |       127.0.0.1 | GET      "/api/status"
[GIN] 2024/02/09 - 07:00:47 | 200 |    1.0085288s |       127.0.0.1 | GET      "/api/status"
Game world settings saved successfully.
Engine settings saved successfully.
[GIN] 2024/02/09 - 07:00:50 | 200 |    1.0082013s |       127.0.0.1 | GET      "/api/status"
2024/02/09 07:00:51 启动命令: C:\Program Files (x86)\Steam\Steam.exe -applaunch 2394010 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
2024/02/09 07:00:51 Game server restarted successfully
2024/02/09 07:00:51 Game server started successfully with PID 23248
2024/02/09 07:00:51 now FreePhysicalMemoryKB: 4.7383124e+07
2024/02/09 07:00:51 Now Memory usage is  29.393643140792847%.
2024/02/09 07:00:51 Memory usage is below 91%. No action required.
[GIN] 2024/02/09 - 07:00:53 | 200 |    1.0089863s |       127.0.0.1 | GET      "/api/status"
[GIN] 2024/02/09 - 07:00:56 | 200 |    1.0032296s |       127.0.0.1 | GET      "/api/status"
Game world settings saved successfully.
Engine settings saved successfully.
[GIN] 2024/02/09 - 07:00:59 | 200 |    1.0082894s |       127.0.0.1 | GET      "/api/status"
[GIN] 2024/02/09 - 07:01:02 | 200 |    1.0112163s |       127.0.0.1 | GET      "/api/status"
[GIN] 2024/02/09 - 07:01:05 | 200 |    1.0062115s |       127.0.0.1 | GET      "/api/status"

**Comment by Hoshinonyaruko** [comment]
fixed
