### ISSUE TITLE
重启不行，关闭不行，保存不行

### ISSUE THREAD

**Issue by dfmjndm** [Hoshinonyaruko/palworld-go#85]
服务器配置的重启，关闭，保存这三个按键都有毛病

保存——点一次保存直接新开一个游戏窗口，原来的都没关掉，点了一下保存我直接服务器cpu炸了

重启——无效，关不掉原来的反而多了一个窗口

关闭——无效，关不掉原来的窗口

这release前都不测试的吗，有个英文的issue也在说这个事情

**Comment by ayakasuki** [comment]
确实很多功能看似实现 但是其实里子没测试做好实际情况。就是刚建好门脸，还一堆bug

**Comment by 2022717137** [comment]
目前已经完善
